// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfT4EDCPWa_R_JLCntCRuUfxVJO9MhS4',
    appId: '1:1094993833277:web:840255a494f476f7382954',
    messagingSenderId: '1094993833277',
    projectId: 'aiapp-15644',
    authDomain: 'aiapp-15644.firebaseapp.com',
    storageBucket: 'aiapp-15644.appspot.com',
    measurementId: 'G-RMRSXX4VZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0V0xTY_rdZ40-ADlwI4k1tEXN17JDm8',
    appId: '1:1094993833277:android:14f31d9f5f6905e7382954',
    messagingSenderId: '1094993833277',
    projectId: 'aiapp-15644',
    storageBucket: 'aiapp-15644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yuhpeXfZ_R5JCR-ts4Zk3-u5pC1yweQ',
    appId: '1:1094993833277:ios:b6ea5f029b9aa57c382954',
    messagingSenderId: '1094993833277',
    projectId: 'aiapp-15644',
    storageBucket: 'aiapp-15644.appspot.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yuhpeXfZ_R5JCR-ts4Zk3-u5pC1yweQ',
    appId: '1:1094993833277:ios:be4a7851ab7a3f30382954',
    messagingSenderId: '1094993833277',
    projectId: 'aiapp-15644',
    storageBucket: 'aiapp-15644.appspot.com',
    iosBundleId: 'com.example.aiApp.RunnerTests',
  );
}
